### ISSUE TITLE
1.11 Version

### ISSUE THREAD

**Issue by Darkere** [gr8pefish/BedBugBuster#1]
Hey I am currently getting plagued by that bug every second time I sleep on 1.11 any chance on a version for that?

**Comment by gr8pefish** [comment]
Yeah, I was going to work on it today actually :)

I have a bunch of school work to do, and finals are coming up, so I can't _guarantee_ a quick release, but know that it is in the works!

**Comment by gr8pefish** [comment]
Alright, that was easier than expected.

The mod is available for 1.11 on CurseForge already. Enjoy!
