### ISSUE TITLE
Kick button doesn't appear

### ISSUE THREAD

**Issue by Nachtus01** [gr8pefish/BedBugBuster#4]
but technically speaking, it's a compatibility issue, I believe. I have this mod as well as another mod, Simulated Nights. I didn't expect an issue, since, from what I have read, neither mod actually changes the way sleep works, but with both mods installed, I do not get a kick button above the leave button when sleeping. There is no crashes or anything. I can reproduce the fact there is no button, but, it just looks like a normal minecraft sleep screen, so not sure how that would be helpful at all, lol. Anyways, I am not sure if this has to do with the fact that the other mod simulates the ticks that should occur while sleeping, or what, but thought if you could talk to the other mod creator to see if its possible to fix the incompatibility, than these two mods would be amazing together, as I still do have occasional issues of getting stuck in bed. I probably shouldn't be surprised as getting stuck in bed happens in real life too, but I'm not always sure I want a kick button for that, lol.  But you know what they say, "Life imitates art, and art imitates life."

**Comment by gr8pefish** [comment]
Haha I like your outlook on life.

I'll look into it; my guess is that we both are trying to modify the same screen and their code is (unintentionally) overriding mine or modifying the screen so my button never appears.

**Comment by Nachtus01** [comment]
Haha! Yeah, I kinda like my outlook too, which, of course, is a 1000% totally unbiased opinion....naturally, lol. Seriously though. You might be right about the button, but I also noticed another issue, and that I can't open chat to type /kick, so there's something more going on. I thought about removing both jars and re-installing them, changing the install order to see if that would make a difference, but jars don't technically install so I am not really sure there would be a benefit there. And unlike other modded games I've played, (skyrim, sims, etc), I haven't seen anything in any forums about load order being of any importance. Since I am not getting error messages....a little guidance to assist you in troubleshooting this would be appreciated.

**Comment by gr8pefish** [comment]
Just to confirm for you: Load order should _not_ matter in modded MC.

That is very strange that the kick command isn't working either; that indicates to me that there may be some larger issue with the mod. I'll look into it later this week and see if I can't figure it out.

If you'd like to help, try and see if it (the command if the bug is hard to replicate) works with only Bed Bugs installed, as I want to make sure it is a mod compat issue. Also, a comprehensive mod list would be nice.

Thanks

**Comment by Nachtus01** [comment]
I can confirm that Bed Bugs works on it’s own. Simulated nights is a recently added mod. As requested, I have attached a zip file that contains the following 3 items; 1. A copy of the overrides folder so you can look at the configs files to see if there may be a correlation. 2. The manifest.json file so you can see what forge versions, twitch version, etc. I am using. 3. An html file listing all the mods in my pack.
I hope that will be sufficient so I don’t have to continue pestering you when I am sure you have better things to do with your time than deal with a compatibility issue….which reminds me, thanks for humoring me. I do appreciate all the effort.

Sent from Mail for Windows 10

**Comment by gr8pefish** [comment]
~~Can you duplicate the issue without Simulated Nights? If not, I'm going to close the issue.~~
I need to read, it's been a while, but still :P

Thanks!
